title: Derin Gezgin
description: Personal website for Derin Gezgin
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

# GitHub Pages settings
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# Exclude from processing
exclude:
  - .git/
  - .github/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - .DS_Store 